### ISSUE TITLE
Runcible Cargo Bug

### ISSUE THREAD

**Issue by kpeamon** [firstmethod/Eamon-CS#25]
I just played through A runcible cargo. I managed to complete it, since I had an old map lying around, which told me which two objects were in the crate in the basement of the university. But the game does not tell the player about these two objects. If I try to open the crate, I am just told that it is already open. Thus the player cannot know which objects are in the crate and thus cannot remove them from the crate. I think there is a similar problem with the lectern in the classroom.

**Comment by firstmethod** [comment]
Thanks for the feedback!

Like Eamon Deluxe the player should be able to inventory the open crate to get a list of its contents:  inv crate

If the crate is closed and then opened again it should also display its contents.

The same goes with the lecturn.

The hints command is also directly from EDX and details some of these subtlties but thats a bit of tribal knowledge.

Maybe I'll look into some enhancements that auto display open container contents....

This kind of info will also likely be included in the WorkingDraft.pdf doc i just uploaded yesterday... a work in progress

Thanks again,
M. Penner

**Comment by firstmethod** [comment]
Well its been so long since i actually played the EDX version I had forgotten inventory on containers is an ECS feature.  I do say feature because i like the symmetry with inventory on NPCs and the way it really cuts down on the  text clutter.  But this is a game nuance that needs to be better conveyed.  

That said I do like the concept of a half way point where a game designer could opt to make one or more containers - and monsters for that matter - optionally auto inventoryable when look/examine command is used.  This behavior would default to off but could work on any or all containers/monsters on a game by game basis.

I think i'll look into it.

Thanks again
M. Penner

**Comment by firstmethod** [comment]
Okay... I did some research:

The crate and lectern are behaving as designed.  The inventory command works with both as expected.

Action items:
1.  Improve documentation relating to the use of Inventory w/containers; be more explicit about the existence of the Hints command (specifically the EAMON CS 1.4 GENERAL HELP etc sections).
2.  Implement support for optional auto-inventory of open containers/friendly monsters when look/examine command is used.  Defaults to disabled (current behavior).  Can be enabled by designers on a game by game and object by object basis.
