### ISSUE TITLE
Eamon.Desktop.snl projects fail to load in newest version of Visual Studio

### ISSUE THREAD

**Issue by kpeamon** [firstmethod/Eamon-CS#32]
Many years ago, I have been programming a bit of Basic and a bit of C++ (I think it was called), so I was optimistic about making a custom adventure with Eamon CS. But I quickly ran into a problem:

I have installed the newest version of Visual Studio Community. When I try to open "Eamon.Desktop.sln", I am told that the seven included projects must be modified by Visual Studio in order to open them in this version of Visual Studio:
![One-way upgrade](https://user-images.githubusercontent.com/37862556/73078140-dfa58b80-3ec1-11ea-97ce-c925f32abcd0.png)

If I choose not to make such a one-way upgrade, the projects are not opened (needs migration) and if I allow Visual Studio to make the one-way upgrade, each project fail to load and give the error:

The SDK 'Microsoft.NET.Sdk' specified could not be found.

If I allow the one-way upgrade, I can see the code of all projects that the first line is:

`<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">`

I suppose this is the problem. Since you are experienced in Visual Studio perhaps it is easy for you to explain what I need to do to solve this problem?
Thanks
Ken

**Comment by firstmethod** [comment]
Hi Ken, just a quick couple of thoughts.  I assume you are using the latest VS 2019 that you got at the link in the Prerequisites section of the workingdraft.pdf.  If you can play the game but VS fails to load it correctly it might mean you only have the .NET Core and .NET Framework runtime installed rather than the SDKs.  Did you download and install in the correct order all files listed in Prerequisites section specifically for Programmers? If so, I may need you to provide some additional info, I'll post a follow up later.

Thanks, Mike

**Comment by kpeamon** [comment]
Oh, you are right! I had installed only the gamer prerequisites. I just uninstalled VS and followed you recommended install order for programmers, so everything works fine now!
