### ISSUE TITLE
Option "2. Start over (saved games will be deleted)" crashes the game

### ISSUE THREAD

**Issue by kpeamon** [firstmethod/Eamon-CS#33]
I just downloaded "Eamon-CS-master.zip" again to make sure that I hadn't messed with the files before I verified this bug, but the bug is still here.

I have tested it in 4 adventures:
1. Wrenhold's Secret Vigil
2. The Temple Of Ngurct
3. Stronghold of Kahr-Dur
4. A Runcible Cargo

They all behave the same: If I die in a fight, I get the question "You have perished. Now what?" and I choose option 2 (Start over), the game shuts down, i.e. the terminal window closes.

Everything else seems to work fine.

I am playing on a danish Windows 10 machine. I am starting the game via the bat-files in the Quicklaunch-folder. I have both tried starting the game from the Main Hall and starting the game via the Resume[gamename].bat files. In both cases, if I die and choose option 2. Start over, the game crashes.

**Comment by firstmethod** [comment]
Hi Ken,

Believe it or not, this sounds like intended behavior.  Selecting 2 (start over) deletes all save game files for the adventure.  Then when you run Resume[gamename].bat again, it will be as though you just arrived from the Main Hall.  If this is not what you're seeing (your save games are gone and running Resume[gamename].bat still works), please let me know.

But you're right, it's really abrupt the way the screen just terminates and it is easy to see how it might appear to be a crash.  I think I will fix that by putting in a message along the lines "Your save games have been deleted." then "Press any key to continue."

Thanks again, this is really helpful.
Mike

**Comment by kpeamon** [comment]
Ah - okay it was intended. I expected the "Start over" option to work as in Eamon Deluxe and Eamon Remastered. In these "Start over" restarts the adventure and the save games are not deleted. Eamon Remastered shows the intro-story again, whereas Eamon Deluxe doesn't.
I  think this would be more helpful since I often find myself wanting to restart to check if I missed something at the beginning of the game/intro but I want to be able to keep my saved games so I can continue from where I left the game. It would have been handy to have that option, but I realize that I can do this in Eamon CS by restoring a saved game and then typing QUIT. I don't think many will need to delete their save-games since they can be overwritten, but I guess that is a matter of taste.

**Comment by firstmethod** [comment]
Well I just tried option 2 in Eamon Deluxe and you're right - it restarts with saved games intact.  Since that logic was based on EDX originally, I wonder if EDX originally did it and they just changed its behavior at some point.  Its been too long, I can't recall.

At any rate, I'll make a note of it and maybe circle back around to doing that at some point.  Right now, unfortunately, there are too many other activities to accommodate it.  

I would mention a 4th option (which is what I do anytime I want to restart with save games intact) - just close the console window and then run a Resume[gamename].bat file from a QuickLaunch folder link on my desktop.  It may be inelegant but it works, and it doesn't harm the system.

I'll still put in those fixes in the mean time because you're right - it does look like a crash.

Regards,
Mike Penner
