### ISSUE TITLE
Test Adventure: Can't get sapphire behind chest

### ISSUE THREAD

**Issue by kpeamon** [firstmethod/Eamon-CS#35]
I am looking on Test Adventure to understand the Dungeon Designer better. I am aware that this "game" is not intended for adventuring but I thought I should mention this as it might be due to a bug in the game engine (or intended?).

When I LOOK BEHIND CHEST in the vault, I am told there is a sapphire. But I can't get it with GET SAPPHIRE or REMOVE SAPPHIRE FROM CHEST.

Should I use another command or is this a bug?

Transcript below (irrelevant  text removed):
> [An iron-bound chest]
An iron-bound chest, its flat top attached with sturdy hinges, sits to the
side of the room, seemingly abandoned.  You notice there is a gap between the
back of the chest and the wall.

> look behind chest
Behind the iron-bound chest you see a deep blue sapphire.

> get sapphire
You can't get that.

> remove sapphire from chest
You must first open it.

> open chest
You open it with the bronze key.
Inside the iron-bound chest you see a deep red ruby.

> remove sapphire from chest
I don't follow you.

> get sapphire
You can't get that.

**Comment by firstmethod** [comment]
Hi Ken, 

I think maybe the containment system needs further clarification in WorkingDraft.pdf.

Here are some guidelines:

1.  Get works only with Artifacts in the Room or with OnContainers (like the rotting tree stump), with the theory that OnContainer contents are directly exposed to the Room so Get makes sense.
2.  Remove works with all Container types, but with these nuances:
     a.  Using "From" as a preposition by itself can only access InContainer content lists and OnContainer content lists.  In other words, it can only access those Artifacts that are Inside or On.
    b.  To access UnderContainer or BehindContainer lists you should use the appropriate preposition 
 or a corresponding synonym (which you can also do for InContainers and OnContainers, incidentally).  Some examples:

  > remove the sapphire behind the chest
  > remove the sapphire from behind the chest
  > remove the sapphire in back of the chest
  > remove the jewelry box under that stump
  > remove jewelry box underneath stump
  > remove the jewelry box from below the stump
  > remove the flashlight on the stump
  > remove flashlight on top of the stump
  > remove flashlight from backpack
  > remove flashlight from in the backpack
  > remove flashlight inside backpack

The parser always decides which containment list you are referring to based on the Preposition, so if all else fails try this:  "remove [directObject] [preposition] [indirectObject]" where preposition = [in|on|under|behind].

Thanks,
Mike P.

**Comment by kpeamon** [comment]
Hi Mike,

Thanks for the clarification. I think it is great that you have introduced LOOK BEHIND/UNDER/ON [object] in Eamon CS.

A disadvantage though is that you need to give additional instructions to the player since it is not likely that they will guess a command like: "REMOVE [object1] BEHIND [object2]". Furthermore, "REMOVE [object]" causes the prompt "From what?". Here it isn't possible to type "BEHIND [object]" or "UNDER [object]".

I have always thought that it would be nice if modern Eamon systems accepted "GET [object]" also for objects inside containers, so that REMOVE was not required anymore, just like most interactive fiction engines. Of course, it shouldn't be possible to GET an object before it has been revealed, so if the object hasn't been revealed yet, it can't be taken. Well, I guess that is just me dreaming :)

**Comment by firstmethod** [comment]
Hi Ken,

Thanks for your insights.  There is more to this story which I did not mention last night.  The behavior I described is only the DEFAULT behavior exhibited by the Eamon CS game engine.  You are looking at Test Adventure which will exhibit the default behavior since it runs on EamonRT.dll.

Things get far more interesting in a customized game.  There are a number of methods that can be overridden in the Artifact class that control containment visibility and access to the parser, but they are not currently documented and need to be.  Also, they may be candidates for future enhancements to further strengthen the containment paradigm.  For example, I just verified I could create a BehindContainer that I could use Get on to retrieve its contents (which a statement like Get Sapphire would work on).  Something like this:

		public override bool ShouldExposeContentsToRoom(ContainerType containerType = ContainerType.In)
		{
			return (Uid == 1 && containerType == ContainerType.Behind) || base.ShouldExposeContentsToRoom(containerType);
		}

As far as the command structure, I tried to keep it consistent and extrapolate from what already exists in Eamon Deluxe.  If I just allow "from" as a preposition for all containment types then there is no point in having them all, so by default you have to use the prepositions (but as mentioned above you can pretty much override everything).  There is an internal consistency to the Look, Put and Remove commands:

   > look behind the chest
   > remove the sapphire [from] behind the chest
   > put the sapphire behind the chest

As to the observation about "REMOVE [object]" just causing "From what?", if you say "REMOVE [object] [from] [in|on|under|behind]" it will respond with "From [inside|on|under|behind] what?".  I am aware of the usefulness of being able to respond to the question "From what?" with "UNDER [object]" and actually looked into implementing it but it turned out to be much harder than expected and I had to roll it back.  I will definitely be revisiting that though as it seems appropriate to support it.

Thanks,
Mike P.

**Comment by kpeamon** [comment]
> For example, I just created an Artifact with Uid 1 that is a BehindContainer which I could use Get on to retrieve its contents (a statement like Get Sapphire would work here, as would any other Command since the contents are exposed to the room).
This is great, I will keep that in mind. As a newbie to C# I would never have figured it out, but it sure is flexible!

**Comment by firstmethod** [comment]
In response to this issue, the CommandParser has been significantly upgraded.  Here is a small gameplay sample from Test Adventure that demonstrates how free-form your input can now be:

> look under

Examine under who or what? stump

Under the rotting tree stump you see a jewelry box.

[Rolling Hills]
You see a rotting tree stump with a flashlight on it.
Obvious paths:  east and west.

> ex

Examine who or what? under

Examine who or what? stump

Under the rotting tree stump you see a jewelry box.

[Rolling Hills]
You see a rotting tree stump with a flashlight on it.
Obvious paths:  east and west.

> remove

Remove who or what? box

From what? from under

From what? stump

Jewelry box retrieved.

[Rolling Hills]
You see a rotting tree stump with a flashlight on it.
Obvious paths:  east and west.

> put the box

Put it in what? under the stump

Done.

[Rolling Hills]
You see a rotting tree stump with a flashlight on it.
Obvious paths:  east and west.

> remove box

From what? under the stump

Jewelry box retrieved.

[Rolling Hills]
You see a rotting tree stump with a flashlight on it.
Obvious paths:  east and west.

>
